name = "SpecialPolynomials"
uuid = "a25cea48-d430-424a-8ee7-0d3ad3742e9e"
authors = ["jverzani <jverzani@gmail.com>"]
version = "0.1.0"

[deps]
AMRVW = "233ec0c9-6b8d-4766-b9a2-a16e389fc38a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
